### ISSUE TITLE
Transfer project to sugarlabs

### ISSUE THREAD

**Issue by davelab6** [walterbender/turtleextras#3]
:D

**Comment by walterbender** [comment]
I need to coordinate this with the Butia team that uses this repo.

**Comment by AlanJAS** [comment]
I not have problems in transfer this repo to new adress. We only change the path in our Makefile and all works again ;-)

**Comment by AlanJAS** [comment]
We are ready for the transfer! Waiting..

**Comment by davelab6** [comment]
Thank you @AlanJAS 🎯

**Comment by walterbender** [comment]
@AlanJAS

I transferred turtleart and turtleextras to github.com/sugarlabs.
To avoid a naming conflict and to respect the new naming conventions, I
named the transferred repos:

activity-turtleart-gtk2
activity-turtleart-extras

regards.

On Thu, Jun 2, 2016 at 2:22 AM, Dave Crossland notifications@github.com
wrote:

> Thank you @AlanJAS https://github.com/AlanJAS 🎯
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/walterbender/turtleextras/issues/3#issuecomment-223205594,
> or mute the thread
> https://github.com/notifications/unsubscribe/ADz74YvZAshu_t2ksNFs0W0sv3VN4jDQks5qHnaVgaJpZM4IlDnK
> .

## 

Walter Bender
Sugar Labs
http://www.sugarlabs.org
http://www.sugarlabs.org

**Comment by davelab6** [comment]
There was a typo 'actvity' - https://github.com/sugarlabs/actvity-turtleart-extras

**Comment by AlanJAS** [comment]
Fixed! https://github.com/sugarlabs/activity-turtleart-extras

**Comment by quozl** [comment]
Well done guys.
